#!/bin/sh

# see https://wiki.debian.org/Courses2005/BuildingWithoutHelper

version=`git tag -l|tail -1`
#version="0.2.2"

if [ ! -e libpsl_${version}.orig.tar.gz ]; then
  wget -O libpsl_${version}.orig.tar.gz https://github.com/rockdaboot/libpsl/archive/${version}.tar.gz
fi

if [ ! -d libpsl-${version} ]; then
  tar xvfz libpsl_${version}.orig.tar.gz
fi
cd libpsl-${version}
#./autogen.sh
#./configure --enable-gtk-doc --prefix=/usr --mandir=\$${prefix}/share/man --infodir=\$${prefix}/share/info
#make dist

#mv libpsl-${version}.tar.gz ../libpsl_${version}.orig.tar.gz
#dh_make --library --createorig --file libpsl-${version}.tar.gz

cp -a ../debian .
debuild -us -uc
