name: libpsl

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        runtime: ["libidn", "libidn2", "libicu"]
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y autopoint autoconf automake gtk-doc-tools libidn2-dev libunistring-dev libicu-dev libidn-dev
    - name: Test with ${{matrix.runtime}}
      run: |
          ./autogen.sh
          CFLAGS="-O0 -Wall -Wextra" ./configure --enable-runtime=${{matrix.runtime}}
          make check
